language: node_js
node_js: stable
install: npm install

jobs:
  include:
    - stage: tests
      node_js: stable
      script:
        - npm run test
    # - stage: semantic release
    #   if: branch = master AND type = push
    #   node_js: stable
    #   script:
    #     - npm run build
    #     - npm run semantic-release
